modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="recipedump"
version="${file.jarVersion}"
displayName="Recipe Dump"
description="Dumps all registered Minecraft recipes to a JSON file"
authors="RecipeDump"

[[dependencies.recipedump]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipedump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"